### ISSUE TITLE
Stacktrace in console on startup - missing tags.

### ISSUE THREAD

**Issue by ProsperCraft** [Yamahari/ILikeWood#44]
ilikewood-release-1.14.3-19w29a
forge .60

```
*[19Jul2019 13:23:04.368] [Server-Worker-9/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read item tag list ilikewood:wall_torches from ilikewood:tags/items/wall_torches.json in data pack ilikewood-release-1.14.3-19w29a.jar
com.google.gson.JsonParseException: Unknown value 'ilikewood:oak_wall_torch'
	at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:156) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
	at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:155) ~[?:?]
	at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
```

**Comment by Yamahari** [comment]
oops, ofc that's error because there's no item for wall torches, only for torches x)

**Comment by Yamahari** [comment]
Should be ficed
